---
- hosts: localhost
  become: yes
  vars_prompt:
    - name: telegram_bot_token
      prompt: "Please paste your Telegram bot token here"
      private: yes
    - name: geonames_username
      prompt: "Please paste your Geonames username here"
      private: yes
  vars:
    - working_directory: "{{ playbook_dir }}"
  tasks:
    - name: Create systemd daemon
      template:
        src: secretariabot.service.j2
        dest: /etc/systemd/system/secretariabot.service
    - name: Reload systemd daemons and start
      systemd:
        daemon_reload: yes
        name: secretariabot
        state: started
